# Generated by Django 5.2.8 on 2025-12-02 07:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='document',
            field=models.ImageField(blank=True, help_text='Optional: upload jpg/jpeg proof (age verification, original proof, etc.)', null=True, upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg'])]),
        ),
    ]
