# Generated by Django 5.2.8 on 2025-12-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_adminaccount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='country',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='member_id',
            new_name='state',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='event',
        ),
        migrations.AddField(
            model_name='registration',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='registration',
            name='level',
            field=models.CharField(blank=True, choices=[('National', 'National'), ('State', 'State'), ('District', 'District')], max_length=20),
        ),
    ]
