# Generated by Django 5.2.8 on 2025-12-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0004_rename_country_registration_district_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('registration_from', models.DateField()),
                ('registration_to', models.DateField()),
                ('event_date', models.DateField()),
                ('event_place', models.CharField(max_length=255)),
                ('age_limit', models.PositiveIntegerField()),
            ],
        ),
    ]
