# Generated by Django 5.2.8 on 2025-12-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0005_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_date',
            new_name='event_from',
        ),
        migrations.AddField(
            model_name='event',
            name='event_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
