# Generated by Django 5.2.7 on 2025-12-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0007_alter_event_options_event_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='categories',
            field=models.TextField(blank=True, help_text="Tournament categories (e.g., Women's Doubles, Mixed Doubles, Men's Doubles). One per line or comma-separated."),
        ),
        migrations.AddField(
            model_name='event',
            name='category_times',
            field=models.TextField(blank=True, help_text="Category start times (e.g., 'Women's Doubles Above 30: 9.00 AM, Mixed Doubles ABOVE 30: 11.00 AM')"),
        ),
        migrations.AddField(
            model_name='event',
            name='entry_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Entry fee amount', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_time',
            field=models.TimeField(blank=True, help_text='Event start time (e.g., 9:00 AM)', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='other_awards',
            field=models.TextField(blank=True, help_text="Other awards or gifts (e.g., 'BEST PLAYER AWARDS & OTHER SURPRISING GIFTS')"),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_deadline_time',
            field=models.TimeField(blank=True, help_text='Registration deadline time (e.g., 8:00 PM)', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='rules',
            field=models.TextField(blank=True, help_text='Tournament rules. One rule per line.'),
        ),
        migrations.AddField(
            model_name='event',
            name='runner_prize',
            field=models.CharField(blank=True, help_text="Runner-up prize (e.g., '1500+Trophy')", max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='semifinalist_prize',
            field=models.CharField(blank=True, help_text="Semifinalist prize (e.g., 'Trophy')", max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='winner_prize',
            field=models.CharField(blank=True, help_text="Winner prize (e.g., '2500+Trophy')", max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='age_limit',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='document',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
