# Generated by Django 5.2.7 on 2025-12-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0008_add_tournament_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='age_limit',
            field=models.CharField(blank=True, help_text='Global age limit (optional - age limits are now part of categories)', max_length=100),
        ),
    ]
