# Generated by Django 5.2.7 on 2025-12-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0009_make_age_limit_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='categories',
            field=models.TextField(blank=True, help_text="Tournament categories with start times. Format: 'Category Name Age Limit: HH:MM' (e.g., 'Women's Doubles Below 30: 12:00'). One per line or comma-separated."),
        ),
        migrations.AlterField(
            model_name='event',
            name='category_times',
            field=models.TextField(blank=True, help_text='[Legacy field] Category start times. Categories now include times in the categories field. This field is kept for backward compatibility.'),
        ),
    ]

