# Generated by Django 5.2.7 on 2025-12-12 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0010_alter_event_categories_alter_event_category_times'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('event_conducted_date', models.DateField(help_text='Date when the event was conducted')),
                ('poster', models.BinaryField(blank=True, editable=True, help_text='Event poster image stored as binary (JPG/JPEG/PNG)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Completed Event',
                'verbose_name_plural': 'Completed Events',
                'ordering': ['-event_conducted_date'],
            },
        ),
        migrations.CreateModel(
            name='EventResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(help_text='Name of the completed event', max_length=200)),
                ('event_date', models.DateField(help_text='Date when the event was conducted')),
                ('winner', models.CharField(blank=True, help_text='Winner(s) of the event', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event Result',
                'verbose_name_plural': 'Event Results',
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='EventResultImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.BinaryField(help_text='Event image stored as binary (JPG/JPEG/PNG)')),
                ('image_order', models.PositiveIntegerField(default=0, help_text='Order of image display')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='registrations.eventresult')),
            ],
            options={
                'verbose_name': 'Event Result Image',
                'verbose_name_plural': 'Event Result Images',
                'ordering': ['image_order', 'created_at'],
            },
        ),
    ]
